Task_1_1_2
andrew-kozubenko/OOP pull request #10
Opened 2023-10-04 15:40 UTC by andrew-kozubenko

Task_1_1_2

2023-10-08 11:53 UTC, BIGNIKi commented
Codestyle поправь, чтобы гиту нравилось
![image](https://github.com/andrew-kozubenko/OOP/assets/91887896/cc95cceb-26f9-4734-9c7f-93b752150915)

2023-10-08 12:17 UTC, BIGNIKi requested changes

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/javadoc/allclasses-index.html
> +<!DOCTYPE HTML>
Добавь папку с javadoc в .gitignore, чтобы её не было в репозитории

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/sth.bat
> +javac -d .\out .\java\org\example\Main.java .\java\org\example\Polynomial.java
Bat`ник для второй и последующих задач не нужны.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        this.coefficients = coefficients;
Вот здесь ты делаешь большую ошибку. Напоминаю, что любой массив - это объект, а значит, он передается по ссылке.
Теперь представь, что кто-то создал сущность Polynomial, передал туда некий массив. Потом в коде начал что-то делать с этим массивом, как-то менять его. Дальше начал делать действия с полиномом.
Что будет в итоге? А в итоге результат действий над полиномом будет ошибочен, так как в тот момент, когда ты менял данные массива, у тебя этот массив сразу изменился и в Полиноме, т.к. полином хранит просто ССЫЛКУ на этот массив.
Однозначно нужно делать копию массива, чтобы таких неочевидных проблем не происходило.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public String toString() {
Добавь аттрибут Override для метода. Хочу, чтобы в голове было понимание того, что любой класс неявно наследует от Object различные методы, которые ты можешь переопределить.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equals(Polynomial second) {
Попробуй сделать equals, переопределив метод equals класса Object. Да, будет немного сложнее, зато практика хорошая.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public String toString() {
Сделай, чтобы для полинома, который равен 0, выводился в консоль 0. У тебя сейчас ничего не выводится, а математически верным все-таки будет, если будем видеть ноль.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        int[] res = new int[coefficients.length - degree];
А если полином степени 2, а степень дифференцирования подадут 10? Ты пытаешься создать массив отрицательной длины, в результате чего Java бросит исключение. Надо этот case обрабатывать правильно.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    private final int[] coefficients;
Добавь ещё геттер для этого поля. Вдруг пользователю класса захочется в ходе исполнения узнать, какие коэффициенты задействуются в данном полиноме и провести некие аналитические действия с числами.

2023-10-08 12:17 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equals(Polynomial second) {
На equals тоже надо будет написать тесты.

2023-10-08 12:21 UTC, BIGNIKi requested changes

2023-10-08 12:21 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        int[] res = new int[this.coefficients.length + second.coefficients.length - 1];
Попробуй умножить один пустой полином, на другой. Возникнет исключение. А должно всё хорошо посчитаться и вернуть также пустой полином (где все коэффициенты ноль).

2023-10-12 04:23 UTC, andrew-kozubenko commented
Вроде как все поправил. Даже javadoc комменты для checkstyle написал.)

2023-10-12 07:50 UTC, BIGNIKi requested changes
Очно защитил. Доделать замечания, PR отправить

2023-10-12 07:50 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        return coefficients;
Косяк, исправить.

2023-10-12 07:50 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        return Arrays.equals(this.coefficients, second.coefficients);
Работает не правильно

2023-10-12 07:50 UTC, BIGNIKi commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        if (coefficients.length != 0 && string.length() == 0) {
Доделать

2023-10-15 03:59 UTC, andrew-kozubenko commented
Всё исправил. Для обработки пустых полиномов теперь изначально их создаю с массивом {0}.
public Polynomial(int[] coefficients) {
        if (coefficients.length == 0) {
            this.coefficients = new int[] {0};
        }
        } else {
            this.coefficients = Arrays.copyOf(coefficients, coefficients.length);
        }
    }

2023-10-18 15:01 UTC, BIGNIKi approved these changes
Всё ништяк

2023-10-30 12:54 UTC, merged